// Generated by Replay. Review compile-report.json before running.
import { chromium, type Page } from "playwright";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

function parseArgs(argv: string[]): Map<string, string> {
  const parsed = new Map<string, string>();
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token?.startsWith("--")) continue;
    const equals = token.indexOf("=");
    if (equals >= 0) parsed.set(token.slice(2, equals), token.slice(equals + 1));
    else {
      const next = argv[index + 1];
      if (next === undefined || next.startsWith("--")) throw new Error(`Missing value for ${token}`);
      parsed.set(token.slice(2), next);
      index += 1;
    }
  }
  return parsed;
}

const args = parseArgs(process.argv.slice(2));
function getInput(name: string): string {
  const value = args.get(name);
  if (value === undefined) throw new Error(`Missing required input --${name}`);
  return value;
}

// Required CLI inputs: --invoiceUrl

async function ask(prompt: string): Promise<string> {
  const readline = createInterface({ input, output });
  try {
    return await readline.question(`${prompt} `);
  } finally {
    readline.close();
  }
}

async function humanCheckpoint(instruction: string): Promise<void> {
  console.warn(`CHECKPOINT: ${instruction}`);
  await ask("Complete the instruction, then press Enter to continue.");
}

async function humanDecision(condition: string): Promise<boolean> {
  const answer = await ask(`DECISION: ${condition} [y/N]`);
  return /^(y|yes)$/i.test(answer.trim());
}

async function humanVerify(expectation: string): Promise<void> {
  if (!(await humanDecision(`${expectation} — is this true?`))) {
    throw new Error(`Human check failed: ${expectation}`);
  }
}

function stopAndFlag(reason: string): never {
  throw new Error(`STOP_AND_FLAG: ${reason}`);
}

async function runWorkflow(page: Page): Promise<void> {
  console.log("Step: Review the invoice totals");
  await page.goto(getInput("invoiceUrl"));
  await humanVerify("Verify: The invoice and purchase-order totals are visible");
  if (await humanDecision("the invoice total matches the purchase-order total")) {
    console.log("Step: Approve the invoice");
    await page.locator("[data-action='approve']").click();
    await humanVerify("Verify: The invoice status is Approved");
  } else {
    stopAndFlag("The totals do not match");
  }
}

const browser = await chromium.launch({ headless: false });
try {
  const page = await browser.newPage();
  await runWorkflow(page);
} finally {
  await browser.close();
}
